filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#infect()

" F8 Build & Run, C
nmap <F8> :TagbarToggle<CR>

" Change to directory of the active file
map ,cd :lcd %:h<CR>

" Ctrl-dir navigates between windows
:nmap <silent> <C-h> :wincmd h<CR>
:nmap <silent> <C-j> :wincmd j<CR>
:nmap <silent> <C-k> :wincmd k<CR>
:nmap <silent> <C-l> :wincmd l<CR>

" vpaste.net
map vp :exec "w !vpaste ft=".&ft<CR>
vmap vp <ESC>:exec "'<,'>w !vpaste ft=".&ft<CR>

" Set the search scan to wrap around the file
set wrapscan

" Set the forward slash to be the slash of note (for Windows).
set shellslash

" Command line hight
set ch=1

" set visual bell -- I hate that damned beeping
set vb

" Allow backspacing over indent, eol, and the start of an insert
set backspace=2

" See :help 'cpoptions' for these ones.  'cpoptions' has a huge
" set of possible options
set cpoptions=ces$

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬
set nolist

" Status line
set stl=%f\ %m\ %r\ Line:\ %l/%L[%p%%]\ Col:\ %c\ Buf:\ #%n\ [%b][0x%B]

" tell Vim to always put a status line in, even if there is only one
" window
set laststatus=2

" Diffs occur side-by-side
set diffopt=vertical

" Hide the mouse pointer while typing
set mousehide

" For Mutt
au BufRead /tmp/mutt-* set tw=72

" This is the timeout used while waiting for user input on a
" multi-keyed macro or while just sitting and waiting for another
" key to be pressed measured in milliseconds.
set timeoutlen=500

" Keep some stuff in the history
set history=100

" These commands open folds
set foldopen=block,insert,jump,mark,percent,quickfix,search,tag,undo

" When the page starts to scroll, keep the cursor 8 lines from
" the top and 8 lines from the bottom
set scrolloff=8

" Allow the cursor to go in to "invalid" places
set virtualedit=all

" For how *I* code these are the best types of settings for
" completion but I get rid of some neat things that you might
" like
set complete=.,w,b,t

" Incrementally match the search.
set incsearch

" Highlight search terms
set hlsearch

" Syntax coloring lines that are too long just slows down the world
set synmaxcol=2048

" Indent C code
set cindent

" Tab behaviour
set ts=8 sts=8 sw=8 noexpandtab

" Column width
set textwidth=80

filetype plugin on

" Only do this part when compiled with support for autocommands
if has("autocmd")
  " Enable file type detection
  filetype on

  " Syntax of these languages is fussy over tabs Vs spaces
  autocmd FileType c,cc,cpp setlocal ts=8 sts=8 sw=8 noexpandtab
  autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
  autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

  " Customisations based on house-style (arbitrary)
  autocmd FileType html         setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType css          setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType javascript   setlocal ts=4 sts=4 sw=4 expandtab
  autocmd FileType coffeescript setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType java         setlocal ts=4 sts=4 sw=4 noexpandtab
  autocmd FileType sql          setlocal ts=3 sts=3 sw=3 expandtab
  autocmd FileType tex          setlocal ts=3 sts=3 sw=3 expandtab spell
  autocmd FileType text         setlocal ts=4 sts=4 sw=4 expandtab spell
  autocmd FileType bib          setlocal ts=3 sts=3 sw=3 expandtab
  autocmd FileType haskell      setlocal sw=4 sts=4 ts=2 autoindent expandtab sta
  autocmd FileType python       setlocal ts=4 sts=4 sw=4 expandtab
  autocmd FileType sh           setlocal ts=4 sts=4 sw=4 expandtab
  autocmd FileType erlang       setlocal ts=4 sts=4 sw=4 expandtab
  autocmd FileType perl         setlocal ts=4 sts=4 sw=4 expandtab

  " Treat .rss files as XML
  autocmd BufNewFile,BufRead *.rss setfiletype xml
  autocmd BufNewFile,BufRead *.gv setfiletype dot
  autocmd BufNewFile,BufRead *.sh setfiletype sh

  " Auto-compile Coffeescript on write
  autocmd BufWritePost *.coffee silent CoffeeMake! -b | cwindow  
  autocmd BufRead,BufNewFile *.txt,*.md setfiletype text

  " Tags files
  autocmd FileType java set tags=~/.tags
endif

" These settings are needed for latex-suite
filetype indent on
filetype plugin on
filetype on
let g:tex_flavor='latex'
set grepprg=grep\ -nH\ $*

